// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package entitlement

import (
	"context"
	"fmt"
	"strings"

	"github.com/AnasSahel/terraform-provider-sailpoint-isc-community/internal/client"
	"github.com/AnasSahel/terraform-provider-sailpoint-isc-community/internal/common"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource              = &entitlementDataSource{}
	_ datasource.DataSourceWithConfigure = &entitlementDataSource{}
)

type entitlementDataSource struct {
	client *client.Client
}

// entitlementDSModel extends the resource model with the lookup-only
// source_id argument, used to narrow a filter-based lookup to one source.
type entitlementDSModel struct {
	entitlementModel
	SourceID types.String `tfsdk:"source_id"`
}

// launcherEntitlementDelayHint is appended to "not found" errors because the
// most common reason for a filter lookup to miss is an entitlement that ISC
// generates asynchronously, such as the one created for an INTERACTIVE_PROCESS
// launcher.
const launcherEntitlementDelayHint = "If this entitlement is generated by ISC (for example the one created for a " +
	"launcher), it may not exist yet: ISC can take up to an hour to generate it. Re-run the plan later."

// NewEntitlementDataSource creates a new data source for SailPoint Entitlement.
func NewEntitlementDataSource() datasource.DataSource {
	return &entitlementDataSource{}
}

func (d *entitlementDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_entitlement"
}

func (d *entitlementDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	c, diags := common.ConfigureClient(ctx, req.ProviderData, "entitlement data source")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	d.client = c
}

func (d *entitlementDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Data source for SailPoint Entitlement.",
		MarkdownDescription: "Data source for SailPoint Entitlement. Look up an entitlement either by `id`, or by any " +
			"combination of `name`, `value`, `attribute` and `source_id`. The two lookup modes are mutually exclusive, " +
			"and a filter lookup must match exactly one entitlement.\n\n" +
			"Filter lookup is how you reach entitlements ISC generates for you, such as the one created for an " +
			"`INTERACTIVE_PROCESS` launcher (named after the launcher), without hardcoding a tenant-specific ID.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The unique identifier of the entitlement. Mutually exclusive with the filter arguments.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The entitlement name. When set without `id`, filters the lookup on an exact name match.",
			},
			"description": schema.StringAttribute{Computed: true},
			"attribute": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The entitlement attribute name. When set without `id`, filters the lookup on an exact match.",
			},
			"value": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The entitlement value. When set without `id`, filters the lookup on an exact match.",
			},
			"source_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The ID of the source the entitlement belongs to. When set without `id`, restricts the lookup to that source.",
			},
			"source_schema_object_type": schema.StringAttribute{Computed: true},
			"privileged":                schema.BoolAttribute{Computed: true},
			"cloud_governed":            schema.BoolAttribute{Computed: true},
			"requestable":               schema.BoolAttribute{Computed: true},
			"owner": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"type": schema.StringAttribute{Computed: true},
					"id":   schema.StringAttribute{Computed: true},
					"name": schema.StringAttribute{Computed: true},
				},
			},
			"source": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"type": schema.StringAttribute{Computed: true},
					"id":   schema.StringAttribute{Computed: true},
					"name": schema.StringAttribute{Computed: true},
				},
			},
			"segments": schema.SetAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"manually_updated_fields": schema.MapAttribute{
				Computed:    true,
				ElementType: types.BoolType,
			},
			"created":  schema.StringAttribute{Computed: true},
			"modified": schema.StringAttribute{Computed: true},
		},
	}
}

func (d *entitlementDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config entitlementDSModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	filters := buildEntitlementFilters(config)
	hasID := isSet(config.ID)

	if !hasID && filters == "" {
		resp.Diagnostics.AddError(
			"Missing required argument",
			"Provide either `id`, or at least one of `name`, `value`, `attribute` or `source_id`.",
		)
		return
	}
	if hasID && filters != "" {
		resp.Diagnostics.AddError(
			"Conflicting arguments",
			"`id` cannot be combined with `name`, `value`, `attribute` or `source_id`. Provide only one lookup mode.",
		)
		return
	}

	var apiResp *client.EntitlementAPI
	if hasID {
		id := config.ID.ValueString()
		tflog.Debug(ctx, "Reading entitlement data source by ID", map[string]any{"id": id})

		ent, err := d.client.GetEntitlement(ctx, id)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error Reading SailPoint Entitlement",
				fmt.Sprintf("Could not read entitlement %q: %s", id, err.Error()),
			)
			return
		}
		apiResp = ent
	} else {
		tflog.Debug(ctx, "Reading entitlement data source by filters", map[string]any{"filters": filters})

		// Two results are enough to tell "exactly one" from "ambiguous".
		ents, err := d.client.ListEntitlements(ctx, filters, 2)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error Listing SailPoint Entitlements",
				fmt.Sprintf("Could not list entitlements with filters %q: %s", filters, err.Error()),
			)
			return
		}
		switch len(ents) {
		case 0:
			resp.Diagnostics.AddError(
				"No entitlement found",
				fmt.Sprintf("No entitlement matched %s. %s", filters, launcherEntitlementDelayHint),
			)
			return
		case 1:
			apiResp = &ents[0]
		default:
			resp.Diagnostics.AddError(
				"Multiple entitlements found",
				fmt.Sprintf("More than one entitlement matched %s. Add `source_id`, `attribute` or `value` to narrow the lookup, or supply `id` directly.", filters),
			)
			return
		}
	}

	if apiResp == nil {
		resp.Diagnostics.AddError("Error Reading SailPoint Entitlement", "Received nil response from SailPoint API")
		return
	}

	resp.Diagnostics.Append(config.FromAPI(ctx, apiResp)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if apiResp.Source != nil && apiResp.Source.ID != "" {
		config.SourceID = types.StringValue(apiResp.Source.ID)
	} else {
		config.SourceID = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}

// buildEntitlementFilters turns the configured lookup arguments into an ISC
// filter expression. It returns "" when no filter argument is set.
func buildEntitlementFilters(m entitlementDSModel) string {
	var clauses []string
	add := func(field string, v types.String) {
		if isSet(v) {
			clauses = append(clauses, fmt.Sprintf("%s eq %s", field, quoteFilterValue(v.ValueString())))
		}
	}
	add("name", m.Name)
	add("value", m.Value)
	add("attribute", m.Attribute)
	add("source.id", m.SourceID)
	return strings.Join(clauses, " and ")
}

// quoteFilterValue wraps s in double quotes for an ISC filter expression,
// escaping backslashes and embedded quotes.
func quoteFilterValue(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

func isSet(v types.String) bool {
	return !v.IsNull() && !v.IsUnknown() && v.ValueString() != ""
}
