// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package transform

import (
	"context"
	"errors"
	"fmt"

	"github.com/AnasSahel/terraform-provider-sailpoint-isc-community/internal/client"
	"github.com/AnasSahel/terraform-provider-sailpoint-isc-community/internal/common"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &transformResource{}
	_ resource.ResourceWithConfigure   = &transformResource{}
	_ resource.ResourceWithImportState = &transformResource{}
)

type transformResource struct {
	client *client.Client
}

func NewTransformResource() resource.Resource {
	return &transformResource{}
}

// Metadata implements resource.Resource.
func (r *transformResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_transform"
}

// Configure implements resource.ResourceWithConfigure.
func (r *transformResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	c, diags := common.ConfigureClient(ctx, req.ProviderData, "transform resource")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.client = c
}

// Schema implements resource.Resource.
func (r *transformResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description:         "Manages a SailPoint Transform. Transforms are used to manipulate attribute values during identity processing.",
		MarkdownDescription: "Manages a SailPoint Transform. Transforms are used to manipulate attribute values during identity processing.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier of the transform. Generated by SailPoint.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the transform. Cannot be changed after creation.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "The type of the transform (e.g., 'lower', 'upper', 'concat', 'substring'). Cannot be changed after creation.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"attributes": schema.StringAttribute{
				MarkdownDescription: "A JSON object containing the transform-specific configuration attributes.",
				Optional:            true,
				Computed:            true,
				CustomType:          jsontypes.NormalizedType{},
			},
		},
	}
}

// Create implements resource.Resource.
func (r *transformResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan transformModel
	tflog.Debug(ctx, "Getting plan for transform resource")
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map resource model to API model
	tflog.Debug(ctx, "Mapping transform resource model to API create request", map[string]any{
		"name": plan.Name.ValueString(),
		"type": plan.Type.ValueString(),
	})
	apiCreateRequest, diags := plan.ToAPICreateRequest(ctx)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create the transform via the API client
	tflog.Debug(ctx, "Creating transform via SailPoint API", map[string]any{
		"name": plan.Name.ValueString(),
		"type": plan.Type.ValueString(),
	})
	transformAPIResponse, err := r.client.CreateTransform(ctx, &apiCreateRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating SailPoint Transform",
			fmt.Sprintf("Could not create SailPoint Transform %q: %s", plan.Name.ValueString(), err.Error()),
		)
		tflog.Error(ctx, "Failed to create SailPoint Transform", map[string]any{
			"name":  plan.Name.ValueString(),
			"error": err.Error(),
		})
		return
	}

	if transformAPIResponse == nil {
		resp.Diagnostics.AddError(
			"Error Creating SailPoint Transform",
			"Received nil response from SailPoint API",
		)
		return
	}

	// Map the API response back to the resource model
	var state transformModel
	tflog.Debug(ctx, "Mapping SailPoint Transform API response to resource model", map[string]any{
		"id":   transformAPIResponse.ID,
		"name": plan.Name.ValueString(),
	})
	resp.Diagnostics.Append(state.FromSailPointAPI(ctx, *transformAPIResponse)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the state
	tflog.Debug(ctx, "Setting state for transform resource", map[string]any{
		"id":   state.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Info(ctx, "Successfully created SailPoint Transform resource", map[string]any{
		"id":   state.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

// Read implements resource.Resource.
func (r *transformResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state transformModel
	tflog.Debug(ctx, "Getting state for transform resource read")
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read the transform from SailPoint
	tflog.Debug(ctx, "Fetching transform from SailPoint", map[string]any{
		"id": state.ID.ValueString(),
	})
	transformResponse, err := r.client.GetTransform(ctx, state.ID.ValueString())
	if err != nil {
		// If resource was deleted outside of Terraform, remove it from state
		if errors.Is(err, client.ErrNotFound) {
			tflog.Info(ctx, "SailPoint Transform not found, removing from state", map[string]any{
				"id": state.ID.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Transform",
			fmt.Sprintf("Could not read SailPoint Transform %q: %s", state.ID.ValueString(), err.Error()),
		)
		tflog.Error(ctx, "Failed to read SailPoint Transform", map[string]any{
			"id":    state.ID.ValueString(),
			"error": err.Error(),
		})
		return
	}

	if transformResponse == nil {
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Transform",
			"Received nil response from SailPoint API",
		)
		return
	}

	// Map the response to the resource model
	tflog.Debug(ctx, "Mapping SailPoint Transform API response to resource model", map[string]any{
		"id": state.ID.ValueString(),
	})
	resp.Diagnostics.Append(state.FromSailPointAPI(ctx, *transformResponse)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the state
	tflog.Debug(ctx, "Setting state for transform resource", map[string]any{
		"id": state.ID.ValueString(),
	})
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Info(ctx, "Successfully read SailPoint Transform resource", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

// Update implements resource.Resource.
func (r *transformResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan transformModel
	tflog.Debug(ctx, "Getting plan for transform resource update")
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get the current state to retrieve the ID
	var state transformModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map resource model to API model
	tflog.Debug(ctx, "Mapping transform resource model to API update request", map[string]any{
		"id":   state.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
	apiUpdateRequest, diags := plan.ToAPIUpdateRequest(ctx)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update the transform via the API client
	tflog.Debug(ctx, "Updating transform via SailPoint API", map[string]any{
		"id": state.ID.ValueString(),
	})
	transformAPIResponse, err := r.client.UpdateTransform(ctx, state.ID.ValueString(), &apiUpdateRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating SailPoint Transform",
			fmt.Sprintf("Could not update SailPoint Transform %q: %s", state.ID.ValueString(), err.Error()),
		)
		tflog.Error(ctx, "Failed to update SailPoint Transform", map[string]any{
			"id":    state.ID.ValueString(),
			"error": err.Error(),
		})
		return
	}

	if transformAPIResponse == nil {
		resp.Diagnostics.AddError(
			"Error Updating SailPoint Transform",
			"Received nil response from SailPoint API",
		)
		return
	}

	// Map the API response back to the resource model
	var newState transformModel
	tflog.Debug(ctx, "Mapping SailPoint Transform API response to resource model", map[string]any{
		"id": state.ID.ValueString(),
	})
	resp.Diagnostics.Append(newState.FromSailPointAPI(ctx, *transformAPIResponse)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the state
	tflog.Debug(ctx, "Setting state for transform resource", map[string]any{
		"id": newState.ID.ValueString(),
	})
	resp.Diagnostics.Append(resp.State.Set(ctx, &newState)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Info(ctx, "Successfully updated SailPoint Transform resource", map[string]any{
		"id":   newState.ID.ValueString(),
		"name": newState.Name.ValueString(),
	})
}

// Delete implements resource.Resource.
func (r *transformResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state transformModel
	tflog.Debug(ctx, "Getting state for transform resource deletion")
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Deleting transform via SailPoint API", map[string]any{
		"id": state.ID.ValueString(),
	})
	err := r.client.DeleteTransform(ctx, state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Deleting SailPoint Transform",
			fmt.Sprintf("Could not delete SailPoint Transform %q: %s", state.ID.ValueString(), err.Error()),
		)
		tflog.Error(ctx, "Failed to delete SailPoint Transform", map[string]any{
			"id":    state.ID.ValueString(),
			"error": err.Error(),
		})
		return
	}
	tflog.Info(ctx, "Successfully deleted SailPoint Transform resource", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

// ImportState implements resource.ResourceWithImportState.
func (r *transformResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import by setting the "id" attribute
	tflog.Debug(ctx, "Importing transform resource", map[string]any{
		"id": req.ID,
	})

	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)

	tflog.Info(ctx, "Successfully imported SailPoint Transform resource", map[string]any{
		"id": req.ID,
	})
}
