// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package source

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/AnasSahel/terraform-provider-sailpoint-isc-community/internal/client"
	"github.com/AnasSahel/terraform-provider-sailpoint-isc-community/internal/common"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &sourceSchemaResource{}
	_ resource.ResourceWithConfigure   = &sourceSchemaResource{}
	_ resource.ResourceWithImportState = &sourceSchemaResource{}
)

type sourceSchemaResource struct {
	client *client.Client
}

// NewSourceSchemaResource creates a new resource for Source Schema.
func NewSourceSchemaResource() resource.Resource {
	return &sourceSchemaResource{}
}

// Metadata implements resource.Resource.
func (r *sourceSchemaResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_source_schema"
}

// Configure implements resource.ResourceWithConfigure.
func (r *sourceSchemaResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	c, diags := common.ConfigureClient(ctx, req.ProviderData, "source schema resource")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.client = c
}

// Schema implements resource.Resource.
func (r *sourceSchemaResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a SailPoint Source Schema.",
		MarkdownDescription: "Manages a SailPoint Source Schema. " +
			"Source schemas define the structure of account and entitlement data from a source. " +
			"Use this resource to create, update, and delete custom schemas for a source.",
		Attributes: map[string]schema.Attribute{
			"source_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the source this schema belongs to. Changing this forces a new resource.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier of the schema. Generated by SailPoint.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the schema (e.g., `account`, `group`). Cannot be changed after creation.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"native_object_type": schema.StringAttribute{
				MarkdownDescription: "The name of the object type on the native system that the schema represents (e.g., `User`, `Group`).",
				Required:            true,
			},
			"identity_attribute": schema.StringAttribute{
				MarkdownDescription: "The name of the attribute used to calculate the unique identifier for an object in the schema. " +
					"Must be set at creation time because updating from null to a value is not supported by the API.",
				Required: true,
			},
			"display_attribute": schema.StringAttribute{
				MarkdownDescription: "The name of the attribute used to calculate the display value for an object in the schema.",
				Optional:            true,
			},
			"hierarchy_attribute": schema.StringAttribute{
				MarkdownDescription: "The name of the attribute whose values represent other objects in a hierarchy. Only relevant to group schemas.",
				Optional:            true,
			},
			"include_permissions": schema.BoolAttribute{
				MarkdownDescription: "Flag indicating whether to include permissions with the object data when aggregating the schema. Defaults to `false`.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
			},
			"features": schema.ListAttribute{
				MarkdownDescription: "Optional features supported by the source. Defaults to an empty list.",
				Optional:            true,
				Computed:            true,
				ElementType:         types.StringType,
				Default:             listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})),
			},
			"configuration": schema.StringAttribute{
				MarkdownDescription: "Extra configuration data for the schema as a JSON object.",
				Optional:            true,
				CustomType:          jsontypes.NormalizedType{},
			},
			"attributes": schema.ListNestedAttribute{
				MarkdownDescription: "The attribute definitions for the schema. " +
					"Required because `identity_attribute` must reference an attribute defined in this list.",
				Required: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the attribute.",
							Required:            true,
						},
						"native_name": schema.StringAttribute{
							MarkdownDescription: "The native name of the attribute on the source system.",
							Optional:            true,
						},
						"type": schema.StringAttribute{
							MarkdownDescription: "The type of the attribute (e.g., `STRING`, `LONG`, `INT`, `BOOLEAN`, `DATE`).",
							Required:            true,
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "The description of the attribute.",
							Required:            true,
						},
						"is_multi": schema.BoolAttribute{
							MarkdownDescription: "Whether the attribute supports multiple values.",
							Optional:            true,
							Computed:            true,
						},
						"is_entitlement": schema.BoolAttribute{
							MarkdownDescription: "Whether the attribute is an entitlement.",
							Optional:            true,
							Computed:            true,
						},
						"is_group": schema.BoolAttribute{
							MarkdownDescription: "Whether the attribute represents a group.",
							Optional:            true,
							Computed:            true,
						},
						"schema": schema.SingleNestedAttribute{
							MarkdownDescription: "A reference to another schema, if applicable (e.g., group membership references the group schema).",
							Optional:            true,
							Attributes: map[string]schema.Attribute{
								"type": schema.StringAttribute{
									MarkdownDescription: "The type of the schema reference (e.g., `CONNECTOR_SCHEMA`).",
									Required:            true,
								},
								"id": schema.StringAttribute{
									MarkdownDescription: "The ID of the referenced schema.",
									Required:            true,
								},
								"name": schema.StringAttribute{
									MarkdownDescription: "The name of the referenced schema.",
									Required:            true,
								},
							},
						},
					},
				},
			},
			"created": schema.StringAttribute{
				MarkdownDescription: "The date the schema was created.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"modified": schema.StringAttribute{
				MarkdownDescription: "The date the schema was last modified.",
				Computed:            true,
			},
		},
	}
}

// Create implements resource.Resource.
func (r *sourceSchemaResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan sourceSchemaModel
	tflog.Debug(ctx, "Getting plan for source schema resource")
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	sourceID := plan.SourceID.ValueString()

	// Map resource model to API model
	tflog.Debug(ctx, "Mapping source schema resource model to API create request", map[string]any{
		"source_id": sourceID,
		"name":      plan.Name.ValueString(),
	})
	apiCreateRequest, diags := plan.ToAPI(ctx)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create the source schema via the API client
	tflog.Debug(ctx, "Creating source schema via SailPoint API", map[string]any{
		"source_id": sourceID,
		"name":      plan.Name.ValueString(),
	})
	createResponse, err := r.client.CreateSourceSchema(ctx, sourceID, &apiCreateRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating SailPoint Source Schema",
			fmt.Sprintf("Could not create SailPoint Source Schema %q for source %q: %s",
				plan.Name.ValueString(), sourceID, err.Error()),
		)
		tflog.Error(ctx, "Failed to create SailPoint Source Schema", map[string]any{
			"source_id": sourceID,
			"name":      plan.Name.ValueString(),
			"error":     err.Error(),
		})
		return
	}

	if createResponse == nil {
		resp.Diagnostics.AddError(
			"Error Creating SailPoint Source Schema",
			"Received nil response from SailPoint API",
		)
		return
	}

	schemaID := createResponse.ID

	// Read back the authoritative state from the API to avoid inconsistencies
	// (the POST response may not include all fields accurately)
	tflog.Debug(ctx, "Reading back source schema after create for authoritative state", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	schemaResponse, err := r.client.GetSourceSchema(ctx, sourceID, schemaID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Source Schema After Create",
			fmt.Sprintf("Source schema was created successfully but could not be read back. Schema ID %q for source %q: %s",
				schemaID, sourceID, err.Error()),
		)
		return
	}

	if schemaResponse == nil {
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Source Schema After Create",
			"Received nil response from SailPoint API when reading back created schema",
		)
		return
	}

	// Map the authoritative GET response to the resource model
	var state sourceSchemaModel
	tflog.Debug(ctx, "Mapping SailPoint Source Schema API response to resource model", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	resp.Diagnostics.Append(state.FromAPI(ctx, *schemaResponse, sourceID)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the state
	tflog.Debug(ctx, "Setting state for source schema resource", map[string]any{
		"source_id": sourceID,
		"schema_id": state.ID.ValueString(),
	})
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Info(ctx, "Successfully created SailPoint Source Schema resource", map[string]any{
		"source_id":   sourceID,
		"schema_id":   state.ID.ValueString(),
		"schema_name": state.Name.ValueString(),
	})
}

// Read implements resource.Resource.
func (r *sourceSchemaResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state sourceSchemaModel
	tflog.Debug(ctx, "Getting state for source schema resource read")
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	sourceID := state.SourceID.ValueString()
	schemaID := state.ID.ValueString()

	// Read the source schema from SailPoint
	tflog.Debug(ctx, "Fetching source schema from SailPoint", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	schemaResponse, err := r.client.GetSourceSchema(ctx, sourceID, schemaID)
	if err != nil {
		// If resource was deleted outside of Terraform, remove it from state
		if errors.Is(err, client.ErrNotFound) {
			tflog.Info(ctx, "SailPoint Source Schema not found, removing from state", map[string]any{
				"source_id": sourceID,
				"schema_id": schemaID,
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Source Schema",
			fmt.Sprintf("Could not read SailPoint Source Schema %q for source %q: %s",
				schemaID, sourceID, err.Error()),
		)
		tflog.Error(ctx, "Failed to read SailPoint Source Schema", map[string]any{
			"source_id": sourceID,
			"schema_id": schemaID,
			"error":     err.Error(),
		})
		return
	}

	if schemaResponse == nil {
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Source Schema",
			"Received nil response from SailPoint API",
		)
		return
	}

	// Map the response to the resource model
	tflog.Debug(ctx, "Mapping SailPoint Source Schema API response to resource model", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	resp.Diagnostics.Append(state.FromAPI(ctx, *schemaResponse, sourceID)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the state
	tflog.Debug(ctx, "Setting state for source schema resource", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Info(ctx, "Successfully read SailPoint Source Schema resource", map[string]any{
		"source_id":   sourceID,
		"schema_id":   schemaID,
		"schema_name": state.Name.ValueString(),
	})
}

// Update implements resource.Resource.
func (r *sourceSchemaResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan sourceSchemaModel
	tflog.Debug(ctx, "Getting plan for source schema resource update")
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get current state to retrieve the ID
	var state sourceSchemaModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	sourceID := state.SourceID.ValueString()
	schemaID := state.ID.ValueString()

	// Map resource model to API model (PUT requires full object with ID)
	tflog.Debug(ctx, "Mapping source schema resource model to API update request", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})

	// Set the ID on the plan model so ToAPIUpdate can include it
	plan.ID = state.ID
	apiUpdateRequest, diags := plan.ToAPIUpdate(ctx)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update the source schema via the API client (PUT)
	tflog.Debug(ctx, "Updating source schema via SailPoint API", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	_, err := r.client.UpdateSourceSchema(ctx, sourceID, schemaID, &apiUpdateRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating SailPoint Source Schema",
			fmt.Sprintf("Could not update SailPoint Source Schema %q for source %q: %s",
				schemaID, sourceID, err.Error()),
		)
		tflog.Error(ctx, "Failed to update SailPoint Source Schema", map[string]any{
			"source_id": sourceID,
			"schema_id": schemaID,
			"error":     err.Error(),
		})
		return
	}

	// Read back the authoritative state from the API to avoid inconsistencies
	// (the PUT response may not include all fields accurately, e.g. boolean fields)
	tflog.Debug(ctx, "Reading back source schema after update for authoritative state", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	schemaResponse, err := r.client.GetSourceSchema(ctx, sourceID, schemaID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Source Schema After Update",
			fmt.Sprintf("Source schema was updated successfully but could not be read back. Schema ID %q for source %q: %s",
				schemaID, sourceID, err.Error()),
		)
		return
	}

	if schemaResponse == nil {
		resp.Diagnostics.AddError(
			"Error Reading SailPoint Source Schema After Update",
			"Received nil response from SailPoint API when reading back updated schema",
		)
		return
	}

	// Map the authoritative GET response to the resource model
	var newState sourceSchemaModel
	tflog.Debug(ctx, "Mapping SailPoint Source Schema API response to resource model", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	resp.Diagnostics.Append(newState.FromAPI(ctx, *schemaResponse, sourceID)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the state
	tflog.Debug(ctx, "Setting state for source schema resource", map[string]any{
		"source_id": sourceID,
		"schema_id": newState.ID.ValueString(),
	})
	resp.Diagnostics.Append(resp.State.Set(ctx, &newState)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Info(ctx, "Successfully updated SailPoint Source Schema resource", map[string]any{
		"source_id":   sourceID,
		"schema_id":   newState.ID.ValueString(),
		"schema_name": newState.Name.ValueString(),
	})
}

// Delete implements resource.Resource.
func (r *sourceSchemaResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state sourceSchemaModel
	tflog.Debug(ctx, "Getting state for source schema resource deletion")
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	sourceID := state.SourceID.ValueString()
	schemaID := state.ID.ValueString()

	tflog.Debug(ctx, "Deleting source schema via SailPoint API", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
	err := r.client.DeleteSourceSchema(ctx, sourceID, schemaID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Deleting SailPoint Source Schema",
			fmt.Sprintf("Could not delete SailPoint Source Schema %q for source %q: %s",
				schemaID, sourceID, err.Error()),
		)
		tflog.Error(ctx, "Failed to delete SailPoint Source Schema", map[string]any{
			"source_id": sourceID,
			"schema_id": schemaID,
			"error":     err.Error(),
		})
		return
	}
	tflog.Info(ctx, "Successfully deleted SailPoint Source Schema resource", map[string]any{
		"source_id":   sourceID,
		"schema_id":   schemaID,
		"schema_name": state.Name.ValueString(),
	})
}

// ImportState implements resource.ResourceWithImportState.
// Import format: source_id/schema_id.
func (r *sourceSchemaResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing source schema resource", map[string]any{
		"import_id": req.ID,
	})

	// Parse the import ID (format: source_id/schema_id)
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: source_id/schema_id, got: %s", req.ID),
		)
		return
	}

	sourceID := parts[0]
	schemaID := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("source_id"), sourceID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), schemaID)...)

	tflog.Info(ctx, "Successfully imported SailPoint Source Schema resource", map[string]any{
		"source_id": sourceID,
		"schema_id": schemaID,
	})
}
